apiVersion: v1
kind: Secret
metadata:
  name: influxdb-creds
type: Opaque
data:
  INFLUXDB_DATABASE: dHdpdHRlcmdyYXBo
  INFLUXDB_HOST: aW5mbHV4ZGI=
  INFLUXDB_PASSWORD: cm9vdA==
  INFLUXDB_USERNAME: cm9vdA==
